---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:{{ php_ppa }}

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest force=yes
  with_items: sys_packages
