---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant
    sys_packages:
      - vim
      - git
      - tree
      - htop
    php_packages:
      - php5-cli
      - php5-curl
      - php5-imagick
      - php5-gd
      - php5-mcrypt
      - libapache2-mod-php5
    php_ppa: php5
    apache_vhosts:
      - {servername: "statamic.dev", server_alias: "project.dev statamic.10.0.1.100.xip.io", documentroot: "/var/www/statamic", serveradmin: "webmaster@localhost"}
  roles:
    - init
    - phpcommon
    - composer
    - apache
